# .rubocop.yml
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/FileOpen:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'spec/factories/**/*'

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Naming/MethodParameterName:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 50

Metrics/MethodLength:
  Max: 200

Layout/LineLength:
  Max: 130
