default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 20) %>
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default





